name: Broadcast Diário

on:
  schedule:
    - cron: '12 9 * * *'  # Todo dia às 9h:12min no horário de Brasília (UTC-3)
  workflow_dispatch:      #  botão de teste manual!

jobs:
  send-tip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python main.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
